### PR TITLE
fixed missing EQCONTOUR and links to sisl-tutorials

### PR DESCRIPTION
**Pull request by zerothi**

### CODE REVIEW

**Comment by zerothi** [comment]
@sofiasanz this should fix #145 and also add the missing EQCONTOUR when doing installation.

Once merged, could you make a new release 0.4.1? Thanks!

**Comment by tfrederiksen** [comment]
Maybe #136 can also go in now?

**Comment by zerothi** [comment]
I mind a little ;) I want things done today, and things thoroughly tested, I need to ship out the installation script ASAP, so introducing something that may be a breaking change can be problematic.  
If you do this, please run through **all** tutorials ASAP and let me know!

**Comment by zerothi** [comment]
#136 will be post-poned to after the workshop.

@sofiasanz could you make a new release? Or are you testing things?

**Comment by sofiasanz** [comment]
I am getting a wrong version when I install `hubbard` (see #147).

Do you know how to fix it?

**Comment by zerothi** [comment]
> > #136 will be post-poned to after the workshop.
> > @sofiasanz could you make a new release? Or are you testing things?
> 
> I am getting a wrong version when I install `hubbard` (see #147).
> 
> Do you know how to fix it?

The problem is that your tags are not annotated! :)

When creating a tag, it is important to make it annotated, yes, this is annoying to remember:

```
git tag -a -m "message" v0.4.1
```
then it will work fine :)

**Comment by sofiasanz** [comment]
> > > #136 will be post-poned to after the workshop.
> > > @sofiasanz could you make a new release? Or are you testing things?
> > 
> > 
> > I am getting a wrong version when I install `hubbard` (see #147).
> > Do you know how to fix it?
> 
> The problem is that your tags are not annotated! :)
> 
> When creating a tag, it is important to make it annotated, yes, this is annoying to remember:
> 
> ```
> git tag -a -m "message" v0.4.1
> ```
> 
> then it will work fine :)

Oooh I see, thanks!
I'll release the new tag, hopefully correctly this time :)

**Comment by zerothi** [comment]
Note I just did a PR and merged it, it should also make it stable against setuptools_scm... The `version_file` is perhaps a bit new, but the other one is deprecated according to their docs...

**Comment by sofiasanz** [comment]
> Note I just did a PR and merged it, it should also make it stable against setuptools_scm... The `version_file` is perhaps a bit new, but the other one is deprecated according to their docs...

Yes, I included it in the last release :) thanks!

**Pull request merged**
