### PR TITLE
WIP: Tutorials

### PR DESCRIPTION
**Pull request by tfrederiksen**
Creating a thread here to discuss the content of the tutorials before merging.

- `MFH_01` finite chiral GNR junction structure (molecule)
- `MFH_02` periodic 16-ZGNR
- `MFH_03` 5-ZGNR device with scattering region

### CODE REVIEW

**Comment by sofiasanz** [comment]
I revised the tutorials and I think they are ready for the workshop as they are now. The only thing is that the links to the other exercises fail when trying to open them if the jupyter notebook is not in the same folder

E.g. In `MFH_2/run.ipynb` I added a link to `MFH_1/run.ipynb` by typing `[MFH_1](../MFH_1/run.ipynb)`, but when I click on it it fails and appears 404 error not found...

... any clues?

**Comment by zerothi** [comment]
I think this is because of a security issue in the jupyter framework. One isn't allowed to go back a directory unless the jupyter notebook was started in the directories you are going to traverse. I have the same problem if one does not start with my tutorial.ipynb.

Also, there are still a couple of references to launchpad, would you mind updating those to the gitlab page? :)

**Comment by zerothi** [comment]
One way to do it is to:
```shell
cd tutorials
jupyter notebook .
```
then go to MFH_02 and then the link works. :)

**Comment by zerothi** [comment]
> By the way, I am checking the links to the siesta project and I haven't seen any to launchpad, however all of them have a typo https://gitlab.com/siesta/-project/siesta instead https://gitlab.com/siesta-project/siesta, so I will fix them :)

Great thanks, i just saw a launchpad link in the tutorials branch `grep launchpad **/*`

**Comment by sofiasanz** [comment]
> Great thanks, i just saw a launchpad link in the tutorials branch `grep launchpad **/*`

Yes I did `grep -r launchpad` to search recursively and didn't see any links to launchpad.... maybe these links appear in the outdated docs folder?

**Pull request merged**
