### PR TITLE
Revised documentation

### PR DESCRIPTION
**Pull request by sofiasanz**

### CODE REVIEW

**Comment by tfrederiksen** [comment]
Hola @sofiasanz , can you also push this as html to `gh-pages`?

**Comment by sofiasanz** [comment]
> Hola @sofiasanz , can you also push this as html to `gh-pages`?

Done!

**Comment by sofiasanz** [comment]
I am not sure why the intersphinx links to other modules in `See Also` boxes appear as `None` :-S
(See for instance https://dipc-cc.github.io/hubbard/docs/latest/api-generated/hubbard.HubbardHamiltonian.html#hubbard.HubbardHamiltonian.DOS)

Any clues??

**Review by tfrederiksen — CHANGES_REQUESTED** [review]
Great work, Sofia!

Just some minor remarks and suggestions:
- Instead of writing detailed examples in the `.rst`, perhaps we could just import the three tutorial notebooks directly? It just requires a link to the notebooks in the `.rst`. (Check out how `sisl` achieves this.) It would both give us some nice graphics for html and avoid having to update code details in the future in two different locations.
- Add funding description somewhere?

**Comment by zerothi** [comment]
> I am not sure why the intersphinx links to other modules in `See Also` boxes appear as `None` :-S
> (See for instance https://dipc-cc.github.io/hubbard/docs/latest/api-generated/hubbard.HubbardHamiltonian.html#hubbard.HubbardHamiltonian.DOS)
> 
> Any clues??

I believe this is due to a couple of different things:

1) you should not use backticks in the "See Also" section
2) I seem to recall that when adding explanation it must be on 1 line, otherwise it is seen as a quotation (rather annoying for long lines), at least I converted mine to 1 liners some time ago....

```python
See Also
------------
sisl.physics.get_distribution
hubbard.NEGF.calc_n: open-boundary ...
```
something like the above should work.

**Comment by sofiasanz** [comment]
> I believe this is due to a couple of different things:
> 
>     1. you should not use backticks in the "See Also" section
> 
>     2. I seem to recall that when adding explanation it must be on 1 line, otherwise it is seen as a quotation (rather annoying for long lines), at least I converted mine to 1 liners some time ago....
> 
> 
> ```python
> See Also
> ------------
> sisl.physics.get_distribution
> hubbard.NEGF.calc_n: open-boundary ...
> ```
> 
> something like the above should work.

Thanks!! It works :-)

**Comment by sofiasanz** [comment]
So there are still some links to `sisl` that don't work :(
See for instance:
https://dipc-cc.github.io/hubbard/docs/latest/api-generated/hubbard.HubbardHamiltonian.html#hubbard.HubbardHamiltonian.DOS
https://dipc-cc.github.io/hubbard/docs/latest/api-generated/hubbard.HubbardHamiltonian.html#hubbard.HubbardHamiltonian.iterate
https://dipc-cc.github.io/hubbard/docs/latest/api-generated/hubbard.HubbardHamiltonian.html#hubbard.HubbardHamiltonian.spin_contamination
https://dipc-cc.github.io/hubbard/docs/latest/api-generated/hubbard.calc_n.html

Probably I am writing the methods wrongly... could you check @zerothi?
Thanks!

**Comment by sofiasanz** [comment]
> Great work, Sofia!
> 
> Just some minor remarks and suggestions:
> 
>     * Instead of writing detailed examples in the `.rst`, perhaps we could just import the three tutorial notebooks directly? It just requires a link to the notebooks in the `.rst`. (Check out how `sisl` achieves this.) It would both give us some nice graphics for html and avoid having to update code details in the future in two different locations.

I like this idea, however some of the tutorials are incomplete parts for people to fill, so they won't work as they are now (for instance MFH_02 or MFH_03). I can change the examples (.rst) files in `docs` to be jupyter notebooks instead.

>     * Add funding description somewhere?

Done!

**Comment by tfrederiksen** [comment]
> I can change the examples (.rst) files in `docs` to be jupyter notebooks instead.

That would be nice! (As long as they are not the solutions to the tutorials.)

**Comment by zerothi** [comment]
> So there are still some links to `sisl` that don't work :(
> See for instance:
> https://dipc-cc.github.io/hubbard/docs/latest/api-generated/hubbard.HubbardHamiltonian.html#hubbard.HubbardHamiltonian.DOS
> https://dipc-cc.github.io/hubbard/docs/latest/api-generated/hubbard.HubbardHamiltonian.html#hubbard.HubbardHamiltonian.iterate
> https://dipc-cc.github.io/hubbard/docs/latest/api-generated/hubbard.HubbardHamiltonian.html#hubbard.HubbardHamiltonian.spin_contamination
> https://dipc-cc.github.io/hubbard/docs/latest/api-generated/hubbard.calc_n.html
> 
> Probably I am writing the methods wrongly... could you check @zerothi?
> Thanks!

Nothing wrong, I haven't added them to the documentation because I am still not sure about their API's...

You may expect at some point I'll revisit these and clean them up...
I will update documentation on my side to enable them.

**Comment by sofiasanz** [comment]
> Nothing wrong, I haven't added them to the documentation because I am still not sure about their API's...
> 
> You may expect at some point I'll revisit these and clean them up...
> I will update documentation on my side to enable them.

Oh OK, just wondering ;)

**Comment by tfrederiksen** [comment]
Hi Sofia, it looks great!!! Just one minor suggestion: Can we revise the example titles and clarify what is meant by "electronic correlations"? I would prefer to say "with onsite Coulomb repulsion". My suggestions for the three titles would be:
- _Isolated structures (molecules)_
- _Periodic structures (perfect crystals, Bloch's theorem)_
- _Open quantum systems (Green's functions)_

**Comment by tfrederiksen** [comment]
Maybe the "Funding" section should also be decoupled from "Publications"?

**Comment by sofiasanz** [comment]
Thanks for the feedback in https://github.com/dipc-cc/hubbard/pull/92#issuecomment-836536934 and https://github.com/dipc-cc/hubbard/pull/92#issuecomment-836539933
You can now see the respective changes in 9e3abbf  and 81e699a :-)

**Pull request merged**
